name: Artefact

on: push

jobs:
  first_jobs:
    name: Primer job
    runs-on: ubuntu-latest

    steps:
      - name: Generar Archivo
        run: |
         echo "Este es un archivo de prueba" >> test.log

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
            name: test-log
            path: test.log

  second_jobs:
        name: segundo job
        needs: first_jobs
        runs-on: ubuntu-latest
    
        steps:
            - name: descargar artefacto
              uses: actions/download-artifact@v4
              with:
                name: test-log

            - name: mostrar contenido
              run: cat test.log    
           