name: Artefact

on: push

jobs:
  first_jobs:
    name: Primer job
    runs-on: ubuntu-latest

    # variable que pasa a otro job
    outputs:
      salida: pepe

    steps:
      - name: Generar Archivo
        run: |
         echo "Este es un archivo de prueba" >> test.log

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
            name: test-log
            path: test.log