name: Strategy

on: push

jobs:
  first_jobs:
    name: Primer job
    runs-on: ubuntu-latest

    strategy:
        matrix:
            message: ["hola", "codigofacilito", "github"]

    steps:
     - name: mostrar mensaje
       run: echo "${{ matrix.message }}"
